### ISSUE TITLE
'yotta version patch' fails on Windows

### ISSUE THREAD

**Issue by bogdanm** [ARMmbed/yotta#116]
```
> yt version patch
info: @0.0.4
Traceback (most recent call last):
  File "C:\Python27\Scripts\yt-script.py", line 9, in <module>
    load_entry_point('yotta==0.0.37', 'console_scripts', 'yt')()
  File "C:\Python27\lib\site-packages\yotta\main.py", line 130, in main
    status = args.command(args, following_args)
  File "C:\Python27\lib\site-packages\yotta\version.py", line 59, in execCommand
    p.writeDescription()
  File "C:\Python27\lib\site-packages\yotta\lib\pack.py", line 206, in writeDescription
    self.vcs.markForCommit(self.description_filename)
  File "C:\Python27\lib\site-packages\yotta\lib\vcs.py", line 148, in markForCommit
    self._execCommands(commands)
  File "C:\Python27\lib\site-packages\yotta\lib\vcs.py", line 129, in _execCommands
    raise Exception('command failed: %s:%s', cmd, err or out)
Exception: ('command failed: %s:%s', ['git', '--work-tree=c:\\work\\mbed\\armmbed\\target-st-nucleo-f401re-gcc', '--git-dir=c:\\work\\mbed\\armmbed\\target-st-nucleo-f401re-gcc\\.git', 'add', 'c:\\work\\mbed\\armmbed\\target-st-nucleo-f401re-gcc\\target.json'], "fatal: unable to access '../../../../../c:\\work\\mbed\\armmbed\\target-st-nucleo-f401re-gcc\\.git/config': Invalid argument\n")
```

Probably a weird path issues.

**Comment by 0xc0170** [comment]
I used it this week, did not have any problem. I'll play with it to see if I can make it fail

**Comment by autopulated** [comment]
Closing for now. Please re-open if this happens again.
