### ISSUE TITLE
Adding owners to targets fails with backtrace

### ISSUE THREAD

**Issue by headlessme** [ARMmbed/yotta#145]
```
Andys-MacBook-Air:Projects andpri01$ yt owners add someone@example.com x86-osx
error: no such modules, "x86-osx"
Traceback (most recent call last):
  File "/usr/local/bin/yt", line 9, in <module>
    load_entry_point('yotta==0.0.41', 'console_scripts', 'yt')()
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yotta-0.0.41-py2.7.egg/yotta/main.py", line 130, in main
    status = args.command(args, following_args)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yotta-0.0.41-py2.7.egg/yotta/owners.py", line 86, in execCommand
    addOwner(args, p)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yotta-0.0.41-py2.7.egg/yotta/owners.py", line 116, in addOwner
    registry_access.addOwner(component.Registry_Namespace, args.module, args.email)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yotta-0.0.41-py2.7.egg/yotta/lib/registry_access.py", line 124, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yotta-0.0.41-py2.7.egg/yotta/lib/registry_access.py", line 107, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/yotta-0.0.41-py2.7.egg/yotta/lib/registry_access.py", line 345, in addOwner
    response.raise_for_status()
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests-2.5.0-py2.7.egg/requests/models.py", line 829, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found
```

This seems to be because yotta is assuming everything is a module, the address it PUTs to is /modules/x86-osx/owners/someone@example.com

**Comment by autopulated** [comment]
`yotta owners [add/remove] <args> <module>` currently only accepts modules. To operate on a target, run the command in the directory of the target you want to modify. The target.json file will be used, and the command should complete successfully.

(`yotta owners ls` does check both modules and targets)

I'm considering 9213147ba41d7de868eae1d7f2101e924a59d60d as resolving this, even though the current behaviour isn't ideal.
