### ISSUE TITLE
pip install yotta --upgrade breaks yotta on windows 7 

### ISSUE THREAD

**Issue by simonqhughes** [ARMmbed/yotta#182]
Hi

This is what happened:

simhug01@E103032 /c/mbed_tools/Python27/Scripts
$ pip install yotta --upgrade
Downloading/unpacking yotta from https://pypi.python.org/packages/source/y/yotta/yotta-0.1.0.tar.gz#md5=9bead7fee77e43e2
669d1e403163604b
  Running setup.py (path:c:\users\simhug01\appdata\local\temp\pip_build_simhug01\yotta\setup.py) egg_info for package yo
tta

Requirement already up-to-date: semantic-version>=2.3.1,<3 in c:\mbed_tools\python27\lib\site-packages (from yotta)
Downloading/unpacking requests>=2.5,<3 from https://pypi.python.org/packages/py2.py3/r/requests/requests-2.6.0-py2.py3-n
one-any.whl#md5=3ab1972bbaf2802d94516fb86b9b0d0b (from yotta)
Requirement already up-to-date: PyGithub>=1.25,<2 in c:\mbed_tools\python27\lib\site-packages (from yotta)
Requirement already up-to-date: colorama>=0.3,<0.4 in c:\mbed_tools\python27\lib\site-packages (from yotta)
Requirement already up-to-date: hgapi>=1.7,<2 in c:\mbed_tools\python27\lib\site-packages (from yotta)
Requirement already up-to-date: Jinja2>=2.7.0,<3 in c:\mbed_tools\python27\lib\site-packages (from yotta)
Requirement already up-to-date: PyCrypto==2.6 in c:\mbed_tools\python27\lib\site-packages (from yotta)
Requirement already up-to-date: PyJWT>=0.3,<0.4 in c:\mbed_tools\python27\lib\site-packages (from yotta)
Requirement already up-to-date: pathlib>=1.0.1,<1.1 in c:\mbed_tools\python27\lib\site-packages (from yotta)
Requirement already up-to-date: jsonschema>=2.4.0,<3.0 in c:\mbed_tools\python27\lib\site-packages (from yotta)
Downloading/unpacking valinor>=0.0.0,<1.0 (from yotta)
  Downloading valinor-0.0.2.tar.gz
  Running setup.py (path:c:\users\simhug01\appdata\local\temp\pip_build_simhug01\valinor\setup.py) egg_info for package
valinor

Requirement already up-to-date: ntfsutils>=0.1.3,<0.2 in c:\mbed_tools\python27\lib\site-packages (from yotta)
Requirement already up-to-date: markupsafe in c:\mbed_tools\python27\lib\site-packages (from Jinja2>=2.7.0,<3->yotta)
Downloading/unpacking pyyaml>=3,<4 (from valinor>=0.0.0,<1.0->yotta)
  Running setup.py (path:c:\users\simhug01\appdata\local\temp\pip_build_simhug01\pyyaml\setup.py) egg_info for package p
yyaml

Downloading/unpacking setuptools from https://pypi.python.org/packages/3.4/s/setuptools/setuptools-14.3-py2.py3-none-any
.whl#md5=fc7acea179a69c7d9bf8b854fe44b029 (from valinor>=0.0.0,<1.0->yotta)
Downloading/unpacking pyOCD>=0.3,<1.0 (from valinor>=0.0.0,<1.0->yotta)
  Running setup.py (path:c:\users\simhug01\appdata\local\temp\pip_build_simhug01\pyOCD\setup.py) egg_info for package py
OCD

Downloading/unpacking project-generator>=0.3,<1.0 (from valinor>=0.0.0,<1.0->yotta)
  Running setup.py (path:c:\users\simhug01\appdata\local\temp\pip_build_simhug01\project-generator\setup.py) egg_info fo
r package project-generator

Installing collected packages: yotta, requests, valinor, pyyaml, setuptools, pyOCD, project-generator
  Found existing installation: yotta 0.0.43
    Uninstalling yotta:
      Successfully uninstalled yotta
  Running setup.py install for yotta

    Installing yotta-script.py script to C:\mbed_tools\Python27\Scripts
    Installing yotta.exe script to C:\mbed_tools\Python27\Scripts
    Installing yotta.exe.manifest script to C:\mbed_tools\Python27\Scripts
    Installing yt-script.py script to C:\mbed_tools\Python27\Scripts
    Installing yt.exe script to C:\mbed_tools\Python27\Scripts
    Installing yt.exe.manifest script to C:\mbed_tools\Python27\Scripts
  Found existing installation: requests 2.5.3
    Uninstalling requests:
      Successfully uninstalled requests
  Running setup.py install for valinor

    Installing valinor-script.py script to C:\mbed_tools\Python27\Scripts
    Installing valinor.exe script to C:\mbed_tools\Python27\Scripts
    Installing valinor.exe.manifest script to C:\mbed_tools\Python27\Scripts
  Running setup.py install for pyyaml
    checking if libyaml is compilable
    Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get it from http://aka.ms/vcpython27
    skipping build_ext

  Found existing installation: setuptools 12.4
    Uninstalling setuptools:
      Successfully uninstalled setuptools
  Running setup.py install for pyOCD

  Running setup.py install for project-generator

    Installing project_generator-script.py script to C:\mbed_tools\Python27\Scripts
    Installing project_generator.exe script to C:\mbed_tools\Python27\Scripts
    Installing project_generator.exe.manifest script to C:\mbed_tools\Python27\Scripts
Successfully installed yotta requests valinor pyyaml setuptools pyOCD project-generator
Cleaning up...

simhug01@E103032 /c/mbed_tools/Python27/Scripts
$
simhug01@E103032 /c/mbed_tools/Python27/Scripts
$ yotta -h
Traceback (most recent call last):
  File "c:\mbed_tools\Python27\Scripts\yotta-script.py", line 9, in <module>
    load_entry_point('yotta==0.1.0', 'console_scripts', 'yotta')()
  File "C:\mbed_tools\Python27\lib\site-packages\pkg_resources\__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\mbed_tools\Python27\lib\site-packages\pkg_resources\__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "C:\mbed_tools\Python27\lib\site-packages\pkg_resources\__init__.py", line 2312, in load
    return self.resolve()
  File "C:\mbed_tools\Python27\lib\site-packages\pkg_resources\__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\__init__.py", line 6, in <module>
    from .main import main
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\main.py", line 14, in <module>
    from . import version
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\version.py", line 14, in <module>
    from .lib import component
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\lib\component.py", line 15, in <module>
    import access
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\lib\access.py", line 13, in <module>
    import target
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\lib\target.py", line 19, in <module>
    import pack
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\lib\pack.py", line 32, in <module>
    import registry_access
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\lib\registry_access.py", line 35, in <module>
    import settings
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\lib\settings.py", line 42, in <module>
    os.path.expanduser(os.path.join(folders.prefix(),'yotta.json'))
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\lib\folders.py", line 27, in prefix
    fsutils.mkDirP(dirname)
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\lib\fsutils.py", line 14, in mkDirP
    os.makedirs(path)
  File "C:\mbed_tools\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 5] Access is denied: 'C:\\Program Files (x86)\\yotta'

simhug01@E103032 /c/mbed_tools/Python27/Scripts
$ yotta
Traceback (most recent call last):
  File "c:\mbed_tools\Python27\Scripts\yotta-script.py", line 9, in <module>
    load_entry_point('yotta==0.1.0', 'console_scripts', 'yotta')()
  File "C:\mbed_tools\Python27\lib\site-packages\pkg_resources\__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\mbed_tools\Python27\lib\site-packages\pkg_resources\__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "C:\mbed_tools\Python27\lib\site-packages\pkg_resources\__init__.py", line 2312, in load
    return self.resolve()
  File "C:\mbed_tools\Python27\lib\site-packages\pkg_resources\__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\__init__.py", line 6, in <module>
    from .main import main
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\main.py", line 14, in <module>
    from . import version
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\version.py", line 14, in <module>
    from .lib import component
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\lib\component.py", line 15, in <module>
    import access
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\lib\access.py", line 13, in <module>
    import target
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\lib\target.py", line 19, in <module>
    import pack
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\lib\pack.py", line 32, in <module>
    import registry_access
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\lib\registry_access.py", line 35, in <module>
    import settings
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\lib\settings.py", line 42, in <module>
    os.path.expanduser(os.path.join(folders.prefix(),'yotta.json'))
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\lib\folders.py", line 27, in prefix
    fsutils.mkDirP(dirname)
  File "C:\mbed_tools\Python27\lib\site-packages\yotta\lib\fsutils.py", line 14, in mkDirP
    os.makedirs(path)
  File "C:\mbed_tools\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 5] Access is denied: 'C:\\Program Files (x86)\\yotta'

simhug01@E103032 /c/mbed_tools/Python27/Scripts
$ type yotta
yotta is hashed (./yotta)

simhug01@E103032 /c/mbed_tools/Python27/Scripts
$ popd
/c/develop/public/jobs/yr2015/2209/work/20150316/mbed /c/develop/public/jobs/yr2015/2209/work/20150316 /c/develop/public
/jobs/yr2015/2209/work/20150318 ~

simhug01@E103032 /c/develop/public/jobs/yr2015/2209/work/20150316/mbed (master)
$ ls -al
total 29
drwxr-xr-x    1 simhug01 Administ     4096 Mar 16 17:03 .
drwxr-xr-x    1 simhug01 Administ        0 Mar 16 16:52 ..
-rw-r--r--    1 simhug01 Administ     4152 Mar 16 16:58 .cproject
drwxr-xr-x    1 simhug01 Administ     4096 Mar 16 16:53 .git
-rw-r--r--    1 simhug01 Administ      246 Mar 16 16:53 .gitattributes
-rw-r--r--    1 simhug01 Administ      767 Mar 16 16:53 .gitignore
-rw-r--r--    1 simhug01 Administ      832 Mar 16 16:58 .project
-rw-r--r--    1 simhug01 Administ      223 Mar 16 16:53 .travis.yml
-rw-r--r--    1 simhug01 Administ     3363 Mar 16 16:53 CONTRIBUTING.md
-rw-r--r--    1 simhug01 Administ     9280 Mar 16 16:53 LICENSE
-rw-r--r--    1 simhug01 Administ       81 Mar 16 16:53 MANIFEST.in
-rw-r--r--    1 simhug01 Administ     6760 Mar 16 16:53 README.md
drwxr-xr-x    1 simhug01 Administ        0 Mar 16 17:44 build
drwxr-xr-x    1 simhug01 Administ        0 Mar 16 16:53 docs
drwxr-xr-x    1 simhug01 Administ     4096 Mar 16 16:53 libraries
-rw-r--r--    1 simhug01 Administ     1783 Mar 16 16:53 setup.py
drwxr-xr-x    1 simhug01 Administ        0 Mar 16 16:53 travis
drwxr-xr-x    1 simhug01 Administ    12288 Mar 20 10:22 workspace_tools

simhug01@E103032 /c/develop/public/jobs/yr2015/2209/work/20150316/mbed (master)
$ type yotta
yotta is /c/mbed_tools/Python27/Scripts/yotta

simhug01@E103032 /c/develop/public/jobs/yr2015/2209/work/20150316/mbed (master)
$ yotta
Traceback (most recent call last):
  File "c:\mbed_tools\Python27\Scripts\yotta-script.py", line 9, in <module>
    load_entry_point('yotta==0.1.0', 'console_scripts', 'yotta')()
  File "C:\mbed_tools\Python27\lib\site-packages\pkg_resources\__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\mbed_tools\Python27\lib\site-packages\pkg_resources\__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "C:\mbed_tools\Python27\lib\site-packages\pkg_resources\__init__.py", line 2312, in load
    return self.resolve()

**Comment by autopulated** [comment]
This is fixed on master.
