### ISSUE TITLE
Issue using get_yotta.py

### ISSUE THREAD

**Issue by adbridge** [ARMmbed/yotta#206]
With python 2.7.9 installed, i downloaded and executed the get_yotta.py script and got the following error:

C:\work> python c:\python27\scripts\get_yotta.py

Wget package missing, installing now...
Traceback (most recent call last):
  File "c:\python27\scripts\get_yotta.py", line 221, in <module>
    main()
  File "c:\python27\scripts\get_yotta.py", line 212, in main
    bootstrap();
  File "c:\python27\scripts\get_yotta.py", line 178, in bootstrap
    x = subprocess.call(['pip', 'install', '-q','wget']);
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

This is using the 32-bit version of python on a 64-bit windows 7 machine and using powershell as the command shell.

NB. I was having issues with my windows path yesterday so I wouldn't rule out a local issue...

**Comment by adbridge** [comment]
OK down to having some spaces in the path entry - cmd shell really doesn't like this whereas powershell is fine with it!
