### ISSUE TITLE
Python3 : yotta installs but wont run

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/yotta#220]
## Problem
On python3.4 you can install yotta, but then it bombs out when trying to run. It is my understanding that Yotta does not work on Python3 yet, if this is the case it should prevent itself from being installed into python3. If I am incorrect and yotta is supposed to work on python3 then we should figure out what happened here.

## constriants
yotta is being installed from the github repo, not from the pip installer.

## Error 
```shell
╭─jack@elTaishou ~  
╰─➤  yotta
Traceback (most recent call last):
  File "/usr/bin//yotta", line 9, in <module>
    load_entry_point('yotta==0.2.5', 'console_scripts', 'yotta')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/yotta-0.2.5-py3.4.egg/yotta/__init__.py", line 6, in <module>
    from .main import main
  File "/usr/lib/python3.4/site-packages/yotta-0.2.5-py3.4.egg/yotta/main.py", line 14, in <module>
    from . import version
  File "/usr/lib/python3.4/site-packages/yotta-0.2.5-py3.4.egg/yotta/version.py", line 14, in <module>
    from .lib import component
  File "/usr/lib/python3.4/site-packages/yotta-0.2.5-py3.4.egg/yotta/lib/component.py", line 15, in <module>
    import access
  File "/usr/lib/python3.4/site-packages/yotta-0.2.5-py3.4.egg/yotta/lib/access.py", line 11, in <module>
    import component
  File "/usr/lib/python3.4/site-packages/yotta-0.2.5-py3.4.egg/yotta/lib/component.py", line 26, in <module>
    import pack
  File "/usr/lib/python3.4/site-packages/yotta-0.2.5-py3.4.egg/yotta/lib/pack.py", line 32, in <module>
    import registry_access
  File "/usr/lib/python3.4/site-packages/yotta-0.2.5-py3.4.egg/yotta/lib/registry_access.py", line 47, in <module>
    import exportkey
  File "/usr/lib/python3.4/site-packages/yotta-0.2.5-py3.4.egg/yotta/lib/exportkey.py", line 40
    s = pack('>I', n & 0xffffffffL) + s
                                 ^
SyntaxError: invalid syntax

```

## Solution
Either prevent yotta from instllalling on python3, or resolve above issue.

**Comment by autopulated** [comment]
python 3 support is experimental, but most things should work. This is a regression caused by bc91e7a3dedc411db14e6c641168eccbdff498f0
