### ISSUE TITLE
Sending CTRL-C to GDB using 'yotta debug' frequently causes yotta and GDB to exit

### ISSUE THREAD

**Issue by marcuschangarm** [ARMmbed/yotta#253]
Sometimes both yotta and GDB will exit at the same time, other times GDB will exit after a while. 

It seems to be a matter of timing as well, since the error doesn't always happen when CTRL-C is sent.

```
(gdb) c
Continuing.
^CTraceback (most recent call last):
  File "/usr/local/bin/yt", line 9, in <module>
    load_entry_point('yotta==0.4.1', 'console_scripts', 'yt')()
  File "/Library/Python/2.7/site-packages/yotta/main.py", line 189, in main
    status = args.command(args, following_args)
  File "/Library/Python/2.7/site-packages/yotta/debug.py", line 40, in execCommand
    error = target.debug(builddir, args.program)
  File "/Library/Python/2.7/site-packages/yotta/lib/target.py", line 374, in debug
    return self._debugDeprecated(builddir, program)
  File "/Library/Python/2.7/site-packages/yotta/lib/fsutils_posix.py", line 59, in wrapped_fn
    msg = q.get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 117, in get
    res = self._recv()
IOError: [Errno 4] Interrupted system call

Program received signal SIGTRAP, Trace/breakpoint trap.
```

**Comment by autopulated** [comment]
Are you using the latest version 0.4.1? (It contained [this fix](https://github.com/ARMmbed/yotta/commit/7517bc9d334d17f44bc5984fef83e581e7c9f838))

**Comment by autopulated** [comment]
Closing as wontfix, because this behaviour was identified with the now-deprecated `debug` and `debugServer` properties in target.json. Use `scripts.debug` instead.
