### ISSUE TITLE
Ill-formed dependency list needs better error message

### ISSUE THREAD

**Issue by marcuschangarm** [ARMmbed/yotta#27]
In the package.json file, dependency statements with invalid syntax produces unhandled python exception (see below) instead of outputting more informative error messages. 

```
Traceback (most recent call last):
  File "/usr/local/bin/yt", line 9, in <module>
    load_entry_point('yotta==0.0.18', 'console_scripts', 'yt')()
  File "/Library/Python/2.7/site-packages/yotta/main.py", line 87, in main
    status = args.command(args)
  File "/Library/Python/2.7/site-packages/yotta/link.py", line 51, in execCommand
    dropSudoPrivs(lambda: install.execCommand(args))
  File "/Library/Python/2.7/site-packages/yotta/link.py", line 30, in dropSudoPrivs
    r = fn()
  File "/Library/Python/2.7/site-packages/yotta/link.py", line 51, in <lambda>
    dropSudoPrivs(lambda: install.execCommand(args))
  File "/Library/Python/2.7/site-packages/yotta/install.py", line 31, in execCommand
    installDeps(args)
  File "/Library/Python/2.7/site-packages/yotta/install.py", line 63, in installDeps
    available_components = [(c.getName(), c)]
  File "/Library/Python/2.7/site-packages/yotta/lib/component.py", line 426, in satisfyDependenciesRecursive
    provider = provider
  File "/Library/Python/2.7/site-packages/yotta/lib/component.py", line 266, in __getDependenciesRecursiveWithProvider
    provider = provider
  File "/Library/Python/2.7/site-packages/yotta/lib/component.py", line 174, in __getDependenciesWithProvider
    satisfyDep, self.getDependencySpecs(target)
  File "/Library/Python/2.7/site-packages/yotta/lib/component.py", line 167, in satisfyDep
    update_installed
  File "/Library/Python/2.7/site-packages/yotta/lib/component.py", line 413, in provider
    r = access.satisfyVersionByInstalling(name, version_req, working_directory)
  File "/Library/Python/2.7/site-packages/yotta/lib/access.py", line 211, in satisfyVersionByInstalling
    return _satisfyVersionByInstallingVersion(name, version_required, install_into, v)
  File "/Library/Python/2.7/site-packages/yotta/lib/access.py", line 219, in _satisfyVersionByInstallingVersion
    assert(version)
AssertionError
```

**Comment by autopulated** [comment]
This was substantially improved in the merge of #140
