### ISSUE TITLE
'yt lics' fails on a module without installed dependencies

### ISSUE THREAD

**Issue by bogdanm** [ARMmbed/yotta#385]
In a freshly cloned module that doesn't have dependencies installed yet, `yt lics` fails with this error message:

```Traceback (most recent call last):
  File "/usr/local/bin/yt", line 4, in <module>
    yotta.main()
  File "/usr/local/lib/python2.7/dist-packages/yotta/main.py", line 218, in main
    status = args.command(args, following_args)
  File "/usr/local/lib/python2.7/dist-packages/yotta/licenses.py", line 44, in execCommand
    for lic in dep.licenses():
  File "/usr/local/lib/python2.7/dist-packages/yotta/lib/component.py", line 586, in licenses
    return [x['type'] for x in self.description['licenses']]
KeyError: 'licenses'```

**Comment by autopulated** [comment]
Thanks for reporting, this case should probably report that dependencies are missing so the result is incomplete, and recommend that the user runs `yotta install` first.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-894
