### ISSUE TITLE
Missing libffi dependency when installing yotta on Mac OS

### ISSUE THREAD

**Issue by sam-taylor-arm** [ARMmbed/yotta#387]
Just installed yotta on Mac OS 10.10.5 and hit two issues:
 * Missing cython dependency (already reported in mbedmicro/pyOCD#163)
 * Missing libffi dependency

The former is trivially resolved running `pip install cython`.

The later is resolved running `brew install libffi`. 

Terminal log follows for reference:

```
e107250-mac:~ samtay01$ pip install yotta
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting yotta
Requirement already satisfied (use --upgrade to upgrade): semantic-version<3,>=2.3.1 in /usr/local/lib/python2.7/site-packages (from yotta)
Requirement already satisfied (use --upgrade to upgrade): Jinja2<3,>=2.7.0 in /usr/local/lib/python2.7/site-packages (from yotta)
Collecting argcomplete<1.0,>=0.8.0 (from yotta)
  Using cached argcomplete-0.9.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests<3,>=2.4.3 in /usr/local/lib/python2.7/site-packages (from yotta)
Collecting jsonschema<3.0,>=2.4.0 (from yotta)
  Using cached jsonschema-2.5.1-py2.py3-none-any.whl
Collecting cryptography>=0.8 (from yotta)
  Using cached cryptography-1.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): colorama<0.4,>=0.3 in /usr/local/lib/python2.7/site-packages (from yotta)
Requirement already satisfied (use --upgrade to upgrade): PyGithub<2,>=1.25 in /usr/local/lib/python2.7/site-packages (from yotta)
Collecting PyJWT<2.0,>=1.0 (from yotta)
  Using cached PyJWT-1.4.0-py2.py3-none-any.whl
Collecting mbed-test-wrapper<0.1.0,>=0.0.2 (from yotta)
Collecting valinor<1.0,>=0.0.0 (from yotta)
Requirement already satisfied (use --upgrade to upgrade): hgapi<2,>=1.7 in /usr/local/lib/python2.7/site-packages (from yotta)
Collecting intelhex<3.0,>=2.0 (from yotta)
  Using cached intelhex-2.0-py2.py3-none-any.whl
Collecting pathlib<1.1,>=1.0.1 (from yotta)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /usr/local/lib/python2.7/site-packages (from Jinja2<3,>=2.7.0->yotta)
Collecting functools32 (from jsonschema<3.0,>=2.4.0->yotta)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /usr/local/lib/python2.7/site-packages (from cryptography>=0.8->yotta)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.8 in /usr/local/lib/python2.7/site-packages (from cryptography>=0.8->yotta)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/local/lib/python2.7/site-packages (from cryptography>=0.8->yotta)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/site-packages (from cryptography>=0.8->yotta)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/local/lib/python2.7/site-packages (from cryptography>=0.8->yotta)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /usr/local/lib/python2.7/site-packages (from cryptography>=0.8->yotta)
Collecting cffi>=1.1.0 (from cryptography>=0.8->yotta)
  Using cached cffi-1.2.1.tar.gz
Collecting pyyaml<4,>=3 (from valinor<1.0,>=0.0.0->yotta)
Collecting pyOCD<1.0,>=0.3 (from valinor<1.0,>=0.0.0->yotta)
Collecting project-generator<0.8.0,>=0.7.0 (from valinor<1.0,>=0.0.0->yotta)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python2.7/site-packages (from cffi>=1.1.0->cryptography>=0.8->yotta)
Collecting hidapi (from pyOCD<1.0,>=0.3->valinor<1.0,>=0.0.0->yotta)
Collecting argparse (from project-generator<0.8.0,>=0.7.0->valinor<1.0,>=0.0.0->yotta)
  Using cached argparse-1.3.0-py2.py3-none-any.whl
Collecting xmltodict (from project-generator<0.8.0,>=0.7.0->valinor<1.0,>=0.0.0->yotta)
Building wheels for collected packages: cryptography, cffi
  Running setup.py bdist_wheel for cryptography
  Complete output from command /usr/local/opt/python/bin/python2.7 -c "import setuptools;__file__='/private/var/folders/yv/gm0nzvqj4v176t_w2rp5yk1svdyh2q/T/pip-build-gA_GRX/cryptography/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/yv/gm0nzvqj4v176t_w2rp5yk1svdyh2q/T/tmpIyakpapip-wheel-:
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  c/_cffi_backend.c:13:10: fatal error: 'ffi.h' file not found
  #include <ffi.h>
           ^
  1 error generated.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/yv/gm0nzvqj4v176t_w2rp5yk1svdyh2q/T/pip-build-gA_GRX/cryptography/setup.py", line 307, in <module>
      **keywords_with_side_effects(sys.argv)
    File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
      _setup_distribution = dist = klass(attrs)
    File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 268, in __init__
      self.fetch_build_eggs(attrs['setup_requires'])
    File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
      replace_conflicting=True,
    File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 836, in resolve
      dist = best[req.key] = env.best_match(req, ws, installer)
    File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1081, in best_match
      return self.obtain(req, installer)
    File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1093, in obtain
      return installer(requirement)
    File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
      return cmd.easy_install(req)
    File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 629, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 659, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 842, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1070, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1058, in run_setup
      raise DistutilsError("Setup script exited with %s" % (v.args[0],))
  distutils.errors.DistutilsError: Setup script exited with error: command 'clang' failed with exit status 1

  ----------------------------------------
  Failed building wheel for cryptography
  Running setup.py bdist_wheel for cffi
  Complete output from command /usr/local/opt/python/bin/python2.7 -c "import setuptools;__file__='/private/var/folders/yv/gm0nzvqj4v176t_w2rp5yk1svdyh2q/T/pip-build-gA_GRX/cffi/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/yv/gm0nzvqj4v176t_w2rp5yk1svdyh2q/T/tmpcWxi2Qpip-wheel-:
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  Package libffi was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libffi.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'libffi' found
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.10-x86_64-2.7
  creating build/lib.macosx-10.10-x86_64-2.7/cffi
  copying cffi/__init__.py -> build/lib.macosx-10.10-x86_64-2.7/cffi
  copying cffi/api.py -> build/lib.macosx-10.10-x86_64-2.7/cffi
  copying cffi/backend_ctypes.py -> build/lib.macosx-10.10-x86_64-2.7/cffi
  copying cffi/cffi_opcode.py -> build/lib.macosx-10.10-x86_64-2.7/cffi
  copying cffi/commontypes.py -> build/lib.macosx-10.10-x86_64-2.7/cffi
  copying cffi/cparser.py -> build/lib.macosx-10.10-x86_64-2.7/cffi
  copying cffi/ffiplatform.py -> build/lib.macosx-10.10-x86_64-2.7/cffi
  copying cffi/gc_weakref.py -> build/lib.macosx-10.10-x86_64-2.7/cffi
  copying cffi/lock.py -> build/lib.macosx-10.10-x86_64-2.7/cffi
  copying cffi/model.py -> build/lib.macosx-10.10-x86_64-2.7/cffi
  copying cffi/recompiler.py -> build/lib.macosx-10.10-x86_64-2.7/cffi
  copying cffi/setuptools_ext.py -> build/lib.macosx-10.10-x86_64-2.7/cffi
  copying cffi/vengine_cpy.py -> build/lib.macosx-10.10-x86_64-2.7/cffi
  copying cffi/vengine_gen.py -> build/lib.macosx-10.10-x86_64-2.7/cffi
  copying cffi/verifier.py -> build/lib.macosx-10.10-x86_64-2.7/cffi
  copying cffi/_cffi_include.h -> build/lib.macosx-10.10-x86_64-2.7/cffi
  copying cffi/parse_c_type.h -> build/lib.macosx-10.10-x86_64-2.7/cffi
  running build_ext
  building '_cffi_backend' extension
  creating build/temp.macosx-10.10-x86_64-2.7
  creating build/temp.macosx-10.10-x86_64-2.7/c
  clang -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c c/_cffi_backend.c -o build/temp.macosx-10.10-x86_64-2.7/c/_cffi_backend.o
  c/_cffi_backend.c:13:10: fatal error: 'ffi.h' file not found
  #include <ffi.h>
           ^
  1 error generated.
  error: command 'clang' failed with exit status 1

  ----------------------------------------
  Failed building wheel for cffi
Failed to build cryptography cffi
Installing collected packages: argcomplete, functools32, jsonschema, cffi, cryptography, PyJWT, mbed-test-wrapper, pyyaml, hidapi, intelhex, pyOCD, argparse, xmltodict, project-generator, valinor, pathlib, yotta
  Running setup.py install for cffi
    Complete output from command /usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/private/var/folders/yv/gm0nzvqj4v176t_w2rp5yk1svdyh2q/T/pip-build-gA_GRX/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/yv/gm0nzvqj4v176t_w2rp5yk1svdyh2q/T/pip-dhvPAn-record/install-record.txt --single-version-externally-managed --compile:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    running install
    running build
    running build_py
    running build_ext
    building '_cffi_backend' extension
    clang -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c c/_cffi_backend.c -o build/temp.macosx-10.10-x86_64-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:13:10: fatal error: 'ffi.h' file not found
    #include <ffi.h>
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1

    ----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/private/var/folders/yv/gm0nzvqj4v176t_w2rp5yk1svdyh2q/T/pip-build-gA_GRX/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/yv/gm0nzvqj4v176t_w2rp5yk1svdyh2q/T/pip-dhvPAn-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/yv/gm0nzvqj4v176t_w2rp5yk1svdyh2q/T/pip-build-gA_GRX/cffi
e107250-mac:~ samtay01$ brew install libffi
==> Downloading https://homebrew.bintray.com/bottles/libffi-3.0.13.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libffi-3.0.13.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Some formulae require a newer version of libffi.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/libffi/lib

==> Summary
🍺  /usr/local/Cellar/libffi/3.0.13: 14 files, 412K

```

**Comment by 0xc0170** [comment]
Related to pyOCD issue mentioned above - v0.5.1 which was released today should fix this

**Comment by autopulated** [comment]
Closing this as it was a pyOCD issue, now fixed. Thanks for the detailed error report!
