### ISSUE TITLE
yotta throws backtrace for github 'moved' URLs

### ISSUE THREAD

**Issue by jaustin** [ARMmbed/yotta#410]
It seems github URLs redirect nice and seamlessly in the browser when a repository is moved

For example:
https://github.com/jamesadevine/BLE_API -->
https://github.com/lancaster-university/BLE_API

However, yotta does not handle the move as smoothly:

using the former in module.json gives a backtrace:
[...]
info: get versions for ble
Traceback (most recent call last):
  File "/usr/local/bin/yt", line 4, in <module>
    yotta.main()
  File "/usr/local/lib/python2.7/site-packages/yotta/main.py", line 229, in main
    status = args.command(args, following_args)
  File "/usr/local/lib/python2.7/site-packages/yotta/update.py", line 28, in execCommand
    updateDeps(args)
  File "/usr/local/lib/python2.7/site-packages/yotta/update.py", line 51, in updateDeps
    available_components = [(c.getName(), c)]
  File "/usr/local/lib/python2.7/site-packages/yotta/lib/component.py", line 559, in satisfyDependenciesRecursive
    test = test
  File "/usr/local/lib/python2.7/site-packages/yotta/lib/component.py", line 354, in __getDependenciesRecursiveWithProvider
    test = test
  File "/usr/local/lib/python2.7/site-packages/yotta/lib/component.py", line 254, in __getDependenciesWithProvider
    satisfyDep, specs
  File "/usr/local/lib/python2.7/site-packages/yotta/lib/component.py", line 236, in satisfyDep
    self.getName()
  File "/usr/local/lib/python2.7/site-packages/yotta/lib/component.py", line 523, in provider
    r = access.satisfyVersionFromSearchPaths(dspec.name, dspec.version_req, search_dirs, update_if_installed)
  File "/usr/local/lib/python2.7/site-packages/yotta/lib/access.py", line 266, in satisfyVersionFromSearchPaths
    v = latestSuitableVersion(name, version_required, registry=_registryNamespaceForType(type))
  File "/usr/local/lib/python2.7/site-packages/yotta/lib/access.py", line 148, in latestSuitableVersion
    remote_component.availableBranches(),
  File "/usr/local/lib/python2.7/site-packages/yotta/lib/github_access.py", line 232, in availableBranches
    GithubComponentVersion('', b[0], b[1], self.name) for b in _getBranchHeads(self.repo).items()
  File "/usr/local/lib/python2.7/site-packages/yotta/lib/github_access.py", line 158, in __init__
    github_spec = re.search('/(repos|codeload.github.com)/([^/]*/[^/]*)/', url).group(2)
AttributeError: 'NoneType' object has no attribute 'group'
[...]

This doesn't seem like the right behaviour.

Instead, it should either fail with a nice warning " X moved to Y" or succeed with the same warning.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-893
