### ISSUE TITLE
yotta link does not seem to work across different windows drives

### ISSUE THREAD

**Issue by radhika-raghavendran** [ARMmbed/yotta#430]
```
D:\GIT\ARMmbed\mbed-client-example-6lowpan>yt link sal-stack-nanostack-private
warning: D:\GIT\ARMmbed\mbed-client-example-6lowpan\yotta_modules\sal-stack-nanostack-private -> C:\yotta\python\Lib\yotta_modules\sal-stack-nanostack-private -> BROKEN
Traceback (most recent call last):
  File "C:\yotta\python\Scripts\yt-script.py", line 9, in <module>
    load_entry_point('yotta==0.7.1', 'console_scripts', 'yt')()
  File "C:\yotta\python\lib\site-packages\yotta\main.py", line 229, in main
    status = args.command(args, following_args)
  File "C:\yotta\python\lib\site-packages\yotta\link.py", line 56, in execCommand
    fsutils.symlink(src, dst)
  File "C:\yotta\python\lib\site-packages\yotta\lib\fsutils.py", line 95, in symlink
    _symlink(source, link_name)
  File "C:\yotta\python\lib\site-packages\yotta\lib\fsutils_win.py", line 47, in _symlink
    junction.create(source, link_name)
  File "C:\yotta\python\lib\site-packages\ntfsutils\junction.py", line 116, in create
    raise Exception("%s is not a directory" % source)
Exception: C:\yotta\python\Lib\yotta_modules\sal-stack-nanostack-private is not a directory

D:\GIT\ARMmbed\mbed-client-example-6lowpan>
```

**Comment by radhika-raghavendran** [comment]
yt link needs to use "sal-stack-nanostack" instead of "sal-stack-nanostack-private".
