### ISSUE TITLE
Yotta doesn't like it when there are .hg files in a directory

### ISSUE THREAD

**Issue by rainierwolfcastle** [ARMmbed/yotta#49]
bobbys-air:frdm_gpio 16.49.33 taylorr$ yotta link-target frdm-k64f
info: /Users/taylorr/Desktop/frdm_gpio 16.49.33/yotta_targets/frdm-k64f -> /usr/local/lib/yotta_targets/frdm-k64f -> /Users/taylorr/Code/GitHub/target-frdm-k64f
bobbys-air:frdm_gpio 16.49.33 taylorr$ yotta target frdm-k64f
bobbys-air:frdm_gpio 16.49.33 taylorr$ yotta build
error: The current directory does not contain a valid module.
bobbys-air:frdm_gpio 16.49.33 taylorr$ yotta init
Enter the module name: <frdm-gpio-16-49-33> 
Enter the initial version: <0.0.0> 
Short description: 
Keywords:  <> 
Author: 
Repository url: 
Homepage: 
What is the license for this project (ISC, MIT, Apache-2 etc.)?  <ISC> 
Is this module an executable? <no> yes
Traceback (most recent call last):
  File "/usr/local/bin/yotta", line 9, in <module>
    load_entry_point('yotta==0.0.28', 'console_scripts', 'yotta')()
  File "/usr/local/lib/python2.7/site-packages/yotta/main.py", line 117, in main
    status = args.command(args)
  File "/usr/local/lib/python2.7/site-packages/yotta/init.py", line 132, in execCommand
    c.writeDescription()
  File "/usr/local/lib/python2.7/site-packages/yotta/lib/pack.py", line 167, in writeDescription
    self.vcs.markForCommit(self.description_filename)
  File "/usr/local/lib/python2.7/site-packages/yotta/lib/vcs.py", line 171, in markForCommit
    self.repo.hg_add(os.path.join(self.worktree, relative_path))
  File "/usr/local/lib/python2.7/site-packages/hgapi/hgapi.py", line 144, in hg_add
    self.hg_command("add", filepath)
  File "/usr/local/lib/python2.7/site-packages/hgapi/hgapi.py", line 118, in hg_command
    return Repo.command(self.path, self._env, *args)
  File "/usr/local/lib/python2.7/site-packages/hgapi/hgapi.py", line 89, in command
    stdout=PIPE, stderr=PIPE, env=env)
  File "/usr/local/Cellar/python/2.7.7_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.7_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by autopulated** [comment]
(closing this as invalid)
