### ISSUE TITLE
what should yotta do with a git repository with no commits yet?

### ISSUE THREAD

**Issue by jrobeson** [ARMmbed/yotta#525]
Currently it generates this if you run yotta build with no commits yet
```
$ yotta build
info: generate for target: nordic-nrf51822-16k-gcc 0.0.9 at ~/src/ytest/yotta_targets/nordic-nrf51822-16k-gcc
Traceback (most recent call last):
  File "/usr/bin/yotta", line 4, in <module>
    yotta.main()
  File "/usr/lib/python2.7/site-packages/yotta/main.py", line 239, in main
    status = args.command(args, following_args)
  File "/usr/lib/python2.7/site-packages/yotta/build.py", line 43, in execCommand
    status = installAndBuild(args, following_args)
  File "/usr/lib/python2.7/site-packages/yotta/build.py", line 117, in installAndBuild
    for error in generator.generateRecursive(c, all_components, builddir, application=app):
  File "/usr/lib/python2.7/site-packages/yotta/lib/cmakegen.py", line 122, in generateRecursive
    self.generate(builddir, modbuilddir, component, new_dependencies, dependencies, recursive_deps, application, toplevel)
  File "/usr/lib/python2.7/site-packages/yotta/lib/cmakegen.py", line 343, in generate
    self.build_info_include_file, build_info_definitions = self.getBuildInfo(component.path, builddir)
  File "/usr/lib/python2.7/site-packages/yotta/lib/cmakegen.py", line 307, in getBuildInfo
    commit_id = vcs_instance.getCommitId()
  File "/usr/lib/python2.7/site-packages/yotta/lib/vcs.py", line 112, in getCommitId
    out, err = self._execCommands([self._gitCmd('rev-parse', 'HEAD')])
  File "/usr/lib/python2.7/site-packages/yotta/lib/vcs.py", line 140, in _execCommands
    raise VCSError("command failed: %s:%s" % (cmd, err or out), returncode=returncode)
yotta.lib.vcs.VCSError: command failed: ['git', '--work-tree=~/src/ytest', '--git-dir=~/src/ytest/.git', 'rev-parse', 'HEAD']:fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by autopulated** [comment]
Well it shouldn't do that, for sure! It should probably leave the VCS build info blank.
