### ISSUE TITLE
Crash when running 'yt clean'

### ISSUE THREAD

**Issue by Intuity** [ARMmbed/yotta#552]
When I ran 'yt clean' on a project I got the following crash from yotta:
```
Traceback (most recent call last):
  File "/Users/peterbirch/Development/Voxel/mbedOS/venv/bin/yt", line 4, in <module>
    yotta.main()
  File "/Users/peterbirch/Development/Voxel/mbedOS/venv/lib/python2.7/site-packages/yotta/main.py", line 239, in main
    status = args.command(args, following_args)
  File "/Users/peterbirch/Development/Voxel/mbedOS/venv/lib/python2.7/site-packages/yotta/clean.py", line 23, in execCommand
    fsutils.rmRf(os.path.join(c.path, 'build'))
  File "/Users/peterbirch/Development/Voxel/mbedOS/venv/lib/python2.7/site-packages/yotta/lib/fsutils.py", line 61, in rmRf
    except WindowsError as e: #pylint: disable=undefined-variable
NameError: global name 'WindowsError' is not defined
```

The environment I'm running under is OS X 10.11 with yotta installed under virtualenv with Python 2.7.10. At the time I was building for the blenano-gcc target.

**Comment by autopulated** [comment]
Thanks for reporting!
