### ISSUE TITLE
PyGithub behaviour changed

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/yotta#573]
The behaviour of PyGithub changed in version 1.26.0 (which is in PyPi now) compared to earlier versions.

get_repo in some cases does not return the base URL, but only the URL path. This in turn confused pyrequests, which complains that there is no protocol specified.

Happens only on dependencies that refer to Github access.

**Comment by markus-becker-tridonic-com** [comment]
Traceback:

```
Fatal Exception, yotta=0.9.2
Traceback (most recent call last):
  File "C:\Python27\Scripts\yotta-script.py", line 9, in <module>
    load_entry_point('yotta==0.9.2', 'console_scripts', 'yotta')()
  File "C:\Python27\lib\site-packages\yotta\main.py", line 240, in main
    status = args.command(args, following_args)
  File "C:\Python27\lib\site-packages\yotta\build.py", line 43, in execCommand
    status = installAndBuild(args, following_args)
  File "C:\Python27\lib\site-packages\yotta\build.py", line 95, in installAndBuild
    install_status = install.execCommand(args, [])
  File "C:\Python27\lib\site-packages\yotta\install.py", line 59, in execCommand
    return installDeps(args, c)
  File "C:\Python27\lib\site-packages\yotta\install.py", line 105, in installDeps
    test = {'own':'toplevel', 'all':True, 'none':False}[args.install_test_deps]
  File "C:\Python27\lib\site-packages\yotta\lib\component.py", line 565, in satisfyDependenciesRecursive
    test = test
  File "C:\Python27\lib\site-packages\yotta\lib\component.py", line 370, in __getDependenciesRecursiveWithProvider
    _processed = _processed
  File "C:\Python27\lib\site-packages\yotta\lib\component.py", line 349, in __getDependenciesRecursiveWithProvider
    test = test
  File "C:\Python27\lib\site-packages\yotta\lib\component.py", line 249, in __getDependenciesWithProvider
    satisfyDep, specs
  File "C:\Python27\lib\site-packages\yotta\lib\component.py", line 231, in satisfyDep
    self.getName()
  File "C:\Python27\lib\site-packages\yotta\lib\component.py", line 551, in provider
    r = access.satisfyVersionByInstalling(dspec.name, dspec.version_req, self.modulesPath())
  File "C:\Python27\lib\site-packages\yotta\lib\access.py", line 297, in satisfyVersionByInstalling
    name, version_required, install_into, v, type=type
  File "C:\Python27\lib\site-packages\yotta\lib\access.py", line 308, in _satisfyVersionByInstallingVersion
    version.unpackInto(working_directory)
  File "C:\Python27\lib\site-packages\yotta\lib\github_access.py", line 191, in unpackInto
    _getTarball(self.url, directory, self.cache_key)
  File "C:\Python27\lib\site-packages\yotta\lib\github_access.py", line 71, in wrapped
    return fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\yotta\lib\github_access.py", line 149, in _getTarball
    response = requests.get(url, allow_redirects=True, stream=True, headers=headers)
  File "C:\Python27\lib\site-packages\requests\api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Python27\lib\site-packages\requests\models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "C:\Python27\lib\site-packages\requests\models.py", line 353, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/repos/markus-becker-tridonic-com/sal/tarball/depend-on-cmsis': No schema supplied. Perhaps you meant http:///repos/markus-becker-tridonic-com/sal/tarball/depend-on-cmsis?
```
