### ISSUE TITLE
yotta checking for updates from git repos

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/yotta#587]
If you have a mixture of git repos and yotta registry modules, yotta exits on the first non-registry module with this traceback:

```
$ yotta outdated
Fatal Exception, yotta=0.9.4
Traceback (most recent call last):
  File "C:\winapps\Python27\Scripts\yotta-script.py", line 9, in <module>
    load_entry_point('yotta==0.9.4', 'console_scripts', 'yotta')()
  File "C:\winapps\Python27\lib\site-packages\yotta\main.py", line 240, in main
    status = args.command(args, following_args)
  File "C:\winapps\Python27\lib\site-packages\yotta\outdated.py", line 37, in execCommand
    return displayOutdated(dependencies, use_colours=(not args.plain))
  File "C:\winapps\Python27\lib\site-packages\yotta\outdated.py", line 58, in displayOutdated
    latest_v = access.latestSuitableVersion(name, '*', registry='modules', quiet=True)
  File "C:\winapps\Python27\lib\site-packages\yotta\lib\access.py", line 108, in latestSuitableVersion
    vers = remote_component.availableVersions()
  File "C:\winapps\Python27\lib\site-packages\yotta\lib\registry_access.py", line 485, in availableVersions
    return _listVersions(self.namespace, self.name)
  File "C:\winapps\Python27\lib\site-packages\yotta\lib\registry_access.py", line 102, in wrapped
    return fn(*args, **kwargs)
  File "C:\winapps\Python27\lib\site-packages\yotta\lib\registry_access.py", line 251, in _listVersions
    'Check that the name is correct, and that it has been published.') % (name, namespace)
yotta.lib.access_common.Unavailable: openais-mbed-common does not exist in the modules registry. Check that the name is correct, and that it has been published.
```

Simplest expected behaviour would be to skip the git repositories and just check the registry modules.
Stretch target: check the git repositories tags or even updates on the specified branch.

**Comment by autopulated** [comment]
Thanks – with #574 it should be possible to improve this.

**Comment by mlnx** [comment]
@markus-becker-tridonic-com Are you still hitting this issue with the latest version of yotta (0.12.2) ?

**Comment by autopulated** [comment]
The crash was fixed in #634. I left this open to track checking for updates from git repos.

**Comment by markus-becker-tridonic-com** [comment]
Not crashing on git anymore. Issue is kept open to track 'checking for updates from git repos' Retitled this issue to reflect this.

**Comment by markus-becker-tridonic-com** [comment]
Closing my yotta issues.
