### ISSUE TITLE
Yotta dies if stdout is closed early

### ISSUE THREAD

**Issue by geky** [ARMmbed/yotta#657]
This isn't very problematic, just nonstandard behaviour I thought might wanted to be noted.

``` bash
$ yt search k64f | head -n 1
frdm-k64f-gcc 2.0.0:
Fatal Exception, yotta=0.12.2
Traceback (most recent call last):
  File "/usr/local/bin/yt", line 4, in <module>
    yotta.main()
  File "/usr/local/lib/python2.7/dist-packages/yotta/main.py", line 205, in main
    status = args.command(args, following_args)
  File "/usr/local/lib/python2.7/dist-packages/yotta/search.py", line 128, in execCommand
    print(formatResult(result, args.plain, short=args.short))
  File "/usr/local/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 36, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 137, in write
    self.write_and_convert(text)
  File "/usr/local/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 162, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "/usr/local/lib/python2.7/dist-packages/colorama/ansitowin32.py", line 171, in write_plain_text
    self.wrapped.flush()
IOError: [Errno 32] Broken pipe
```

**Comment by autopulated** [comment]
:+1: Thanks for reporting, looks like this is (at least in part) a bug in colorama's stdout wrapping for cross-platform colour code compatibility, which you might want to report at https://github.com/tartley/colorama.
