### ISSUE TITLE
yotta AuthTimedOut Exception when mbed.org authentication fails 

### ISSUE THREAD

**Issue by simonqhughes** [ARMmbed/yotta#686]
Hi

I tried to use yotta for the first time on an ubuntu 12.04 machine. The mbed.org authentication failed because it reported I hadnt completed the email verification process. While investigating the problem, yotta timed-out the auth process but experienced and exception, shown below:

simhug01@e102749-lin:/develop/jobs/yr2016/2247/sdh_dev_l1/test$ yt build
info: get versions for linux-native
info: download linux-native@1.0.0 from the public module registry

You need to log in to do this.
Press enter to continue.
Your browser will open to complete login.

waiting for response...
If you are unable to use a browser on this machine, please copy and paste this URL into a browser:
https://yotta.mbed.com/#login/AAAAB3NzaC1yc2EAAAADAQABAAABAQDprvBaY/D69BHDMTMZYQ4HbaPzFjN0f1W8flqvhmAoC/kk9gq1AD/u39tj2W7JgrqkzTVWD97fN7ys2%2BWcLiCDcorPIFlWbBBMAiBALCTRIiTU2XJkp1t3gyXZkVawANqq/IbsxotwB%2B77fJ/mg6PgvuTNZGkGIndaQpyEdtRP8TdQ%2BSt0ZAGZhnRAi8DmSG1HICU7jnm2RMMUojTHRF7G7N6pNXMYb8w5NQVi4Ah0oje7xaqayYgl4YLOi64y7FfEWLoEXYXX3jHBtMiO2%2Bbntw6ZHTXmCUgFZWgsBrqOSTEx2yn0Zo33pwkVAmV8AU%2B2uQMkwtwtz4J/oGbgLxvd
.............
..........................................Fatal Exception, yotta=0.13.1
Traceback (most recent call last):
  File "/usr/local/bin/yt", line 4, in <module>
    yotta.main()
  File "/usr/local/lib/python2.7/dist-packages/yotta/main.py", line 206, in main
    status = args.command(args, following_args)
  File "/usr/local/lib/python2.7/dist-packages/yotta/build.py", line 46, in execCommand
    status = installAndBuild(args, following_args)
  File "/usr/local/lib/python2.7/dist-packages/yotta/build.py", line 70, in installAndBuild
    target, errors = c.satisfyTarget(args.target, additional_config=args.config)
  File "/usr/local/lib/python2.7/dist-packages/yotta/lib/component.py", line 672, in satisfyTarget
    additional_config = additional_config
  File "/usr/local/lib/python2.7/dist-packages/yotta/lib/target.py", line 143, in getDerivedTarget
    type = 'target'
  File "/usr/local/lib/python2.7/dist-packages/yotta/lib/access.py", line 371, in satisfyVersion
    name, version_required, working_directory, type=type, inherit_shrinkwrap = inherit_shrinkwrap
  File "/usr/local/lib/python2.7/dist-packages/yotta/lib/access.py", line 307, in satisfyVersionByInstalling
    name, version_required, install_into, v, type=type, inherit_shrinkwrap = inherit_shrinkwrap
  File "/usr/local/lib/python2.7/dist-packages/yotta/lib/access.py", line 318, in _satisfyVersionByInstallingVersion
    version.unpackInto(working_directory)
  File "/usr/local/lib/python2.7/dist-packages/yotta/lib/registry_access.py", line 447, in unpackInto
    _getTarball(self.url, directory, self.sha256)
  File "/usr/local/lib/python2.7/dist-packages/yotta/lib/registry_access.py", line 100, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yotta/lib/registry_access.py", line 185, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yotta/lib/registry_access.py", line 168, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yotta/lib/registry_access.py", line 154, in wrapped
    auth.authorizeUser(provider=None, interactive=interactive)
  File "/usr/local/lib/python2.7/dist-packages/yotta/lib/auth.py", line 125, in authorizeUser
    raise AuthTimedOut('timed out: please try again.')

Best
Simon

**Comment by autopulated** [comment]
Following offline discussion, this turned out to be due to the "no verified emails found" error page: verifying the email address solved the problem. (closing)
