### ISSUE TITLE
yotta - build errors on Mac/OSX

### ISSUE THREAD

**Issue by gdillen** [ARMmbed/yotta#772]
Hello,

I'm trying to build examples on my Mac/OSX. I get the errors (see below). I installed yotta by using the downloading the packaged yotta app. Any idea what goes wrong?

Thanks.

yotta build
info: get versions for x86-osx-native
warning: connection error: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",), retrying...
warning: connection error: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",), retrying...
warning: connection error: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",), retrying...
warning: connection error: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",), retrying...
error: connection error: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
Traceback (most recent call last):
  File "/Applications/yotta.app/Contents/Resources/workspace/bin/yotta", line 4, in <module>
    yotta.main()
  File "/Applications/yotta.app/Contents/Resources/workspace/lib/python2.7/site-packages/yotta/main.py", line 239, in main
    status = args.command(args, following_args)
  File "/Applications/yotta.app/Contents/Resources/workspace/lib/python2.7/site-packages/yotta/build.py", line 41, in execCommand
    status = installAndBuild(args, following_args)
  File "/Applications/yotta.app/Contents/Resources/workspace/lib/python2.7/site-packages/yotta/build.py", line 64, in installAndBuild
    target, errors = c.satisfyTarget(args.target)
  File "/Applications/yotta.app/Contents/Resources/workspace/lib/python2.7/site-packages/yotta/lib/component.py", line 569, in satisfyTarget
    update_installed = update_installed
  File "/Applications/yotta.app/Contents/Resources/workspace/lib/python2.7/site-packages/yotta/lib/target.py", line 95, in getDerivedTarget
    type = 'target'
  File "/Applications/yotta.app/Contents/Resources/workspace/lib/python2.7/site-packages/yotta/lib/access.py", line 352, in satisfyVersion
    return satisfyVersionByInstalling(name, version_required, working_directory, type=type)
  File "/Applications/yotta.app/Contents/Resources/workspace/lib/python2.7/site-packages/yotta/lib/access.py", line 294, in satisfyVersionByInstalling
    v = latestSuitableVersion(name, version_required, _registryNamespaceForType(type))
  File "/Applications/yotta.app/Contents/Resources/workspace/lib/python2.7/site-packages/yotta/lib/access.py", line 108, in latestSuitableVersion
    vers = remote_component.availableVersions()
  File "/Applications/yotta.app/Contents/Resources/workspace/lib/python2.7/site-packages/yotta/lib/registry_access.py", line 469, in availableVersions
    return _listVersions(self.namespace, self.name)
  File "/Applications/yotta.app/Contents/Resources/workspace/lib/python2.7/site-packages/yotta/lib/registry_access.py", line 110, in wrapped
    errmessage = str(e.message[1])
IndexError: tuple index out of range

**Comment by gdillen** [comment]
This did the job: pip install -U certifi
